export {};

try {
  var first;
  let second;
} catch (err) {
  var third;
  let fourth;
}
